# file location: ${HOME}/Brewfile

# This file is used along with the `brew bundle` command to ensure that required packages and apps are installed.
# Also can be used to ensure that any package/apps that were installed as experimentation are uninstalled from the system.
# For a more detailed explanation of the philosophy/reasoning behind this file, please see https://openfolder.sh/macos-migrations-with-brewfile

# If you are starting such a file on a machine where you have already installed some apps using brew, then use `brew bundle dump` to create this file and avoid starting from scratch. Remember though that this is a 1-time run of this command. In the future, if you regenerate the Brewfile using this command, any custom comments/formatting that you might have done - would be lost.

# If you have also installed some vscode plugins already (manually), then you can use the following command to export that list:
# code --list-extensions

# These are the common shell aliases that I have setup in the `${HOME}/.aliases` file for ease of running/typing (and also don't need to remember all these commands by-heart!)
# alias bcg='brew outdated --greedy'  # List all casks that are outdated like a "dry-run" (and which have version marked as 'latest')
# alias bcug='brew upgrade --greedy'  # Upgrades all casks that are outdated (and which have version marked as 'latest')
# alias bupc='brew bundle check || brew bundle --all --cleanup; brew bundle cleanup -f; brew cleanup --prune=all; brew autoremove; brew upgrade'        # Upgrades and cleans up all regular outdated casks and libs (non-greedy)

# TODO: Need to find brew/cask for:
# Tinkertool

# set global preferences for all 'brew install' commands
cask_args appdir: '/Applications', no_quarantine: true

tap 'romkatv/powerlevel10k'

brew 'bash'
brew 'bat'
brew 'btop'
brew 'curl'
brew 'diff-so-fancy'
brew 'direnv'
brew 'fzy'
brew 'git-extras'
brew 'git-gui'
brew 'git-tools'
brew 'git'
brew 'gradle'
brew 'jhipster' # Note: downloads node latest version as depenency
brew 'mise'
brew 'node'
brew 'powerlevel10k'
brew 'prettyping'
brew 'sonar-scanner'
brew 'vim'
brew 'watchman'
brew 'wget'
brew 'yarn' # Note: downloads node latest version as depenency
brew 'zsh'

# ---------------------------------------------------------------------------------------------------------
# mas is to download apps from app store [regester/login to app store for mas commands to work]---------------------------------------------------------------------------------------------------------
brew 'mas'
# mas 'iBar-Menubar icon control tool', id: 6443843900
# mas 'Velja', id: 1607635845

# cask 'clocker'
# cask 'flycut'
# cask 'keepingyouawake'
cask 'android-studio'
cask 'appcleaner'
cask 'firefox'
cask 'flutter' # Note: downloads dart latest version as depenency
cask 'font-meslo-lg-nerd-font'
cask 'google-chrome'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'keybase'
cask 'postman-agent'
cask 'rancher'
cask 'rectangle'
cask 'stats'
cask 'vscodium'
cask 'whatsapp'
cask 'zoom'

is_vscode_installed = !`which code`.chomp.empty?
if is_vscode_installed
  vscode 'brandonkirbyson.vscode-animations'
  vscode 'britesnow.vscode-toggle-quotes'
  vscode 'dart-code.dart-code'
  vscode 'dart-code.flutter'
  vscode 'davidanson.vscode-markdownlint'
  vscode 'dbaeumer.vscode-eslint'
  vscode 'digitalbrainstem.javascript-ejs-support'
  vscode 'drcika.apc-extension'
  vscode 'eamodio.gitlens'
  vscode 'editorconfig.editorconfig'
  vscode 'esbenp.prettier-vscode'
  vscode 'esbenp.prettier-vscode'
  vscode 'formulahendry.code-runner'
  vscode 'genuitecllc.codetogether'
  vscode 'golang.go'
  vscode 'ibm.output-colorizer'
  vscode 'markosth09.color-picker'
  vscode 'mechatroner.rainbow-csv'
  vscode 'mikestead.dotenv'
  vscode 'mkhl.direnv'
  vscode 'ms-azuretools.vscode-docker'
  vscode 'ms-vscode.atom-keybindings'
  vscode 'ms-vscode.vscode-typescript-next'
  vscode 'nicolasvuillamy.vscode-groovy-lint'
  vscode 'oderwat.indent-rainbow'
  vscode 'orta.vscode-jest'
  vscode 'rebornix.ruby'
  vscode 'redhat.java'
  vscode 'redhat.vscode-yaml'
  vscode 'richie5um2.vscode-sort-json'
  vscode 'shan.code-settings-sync'
  vscode 'sonarsource.sonarlint-vscode'
  vscode 'tchayen.markdown-links'
  vscode 'tyriar.sort-lines'
  vscode 'vscjava.vscode-java-debug'
  vscode 'vscjava.vscode-java-pack'
  vscode 'vscjava.vscode-java-test'
  vscode 'vscjava.vscode-lombok'
  vscode 'vscode-icons-team.vscode-icons'
  vscode 'wayou.vscode-todo-highlight'
  vscode 'wholroyd.jinja'
  vscode 'wingrunr21.vscode-ruby'
  vscode 'wmaurer.change-case'
  vscode 'xaver.clang-format'
  vscode 'yzhang.markdown-all-in-one'
end
