# file location: ${HOME}/Brewfile

# This file is used along with the `brew bundle` command to ensure that required packages and apps are installed.
# Also can be used to ensure that any package/apps that were installed as experimentation are uninstalled from the system.
# For a more detailed explanation of the philosophy/reasoning behind this file, please see https://openfolder.sh/macos-migrations-with-brewfile

# These are the common shell aliases that I have setup in the `${HOME}/.aliases` file for ease of running/typing (and also don't need to remember all these commands by-heart!). If you are using my `${HOME}/.aliases`, they will already be present for you. If not, you can then set these up in the respective dotfile of your choice
# alias bcg='brew outdated --greedy'  # List all casks that are outdated like a "dry-run" (and which have version marked as 'latest')
# alias bcug='brew upgrade --greedy'  # Upgrades all casks that are outdated (and which have version marked as 'latest')
# alias bupc='brew bundle check || brew bundle --all --cleanup; brew bundle cleanup -f; brew cleanup --prune=all; brew autoremove; brew upgrade'
# Upgrades and cleans up all regular outdated casks and libs (non-greedy)

# TODO: Need to find cask for:
#   Ghostty
#   Tinkertool
#   ZoomHider

# set global preferences for all 'brew install' commands
cask_args appdir: '/Applications', fontdir: '/Library/Fonts', no_quarantine: true, adopt: true

# java_present = system('/usr/libexec/java_home --failfast')
is_arm = Hardware::CPU.arm?

tap 'homebrew/services'
tap 'romkatv/powerlevel10k'

# formulae pulled in from homebrew to replace system equivalents to fix any security issues since the OS was released
brew 'bash'
brew 'curl'
brew 'git'
brew 'less'
brew 'vim'
brew 'wget'
brew 'zsh'

# formulae pulled in for base configs
brew 'diff-so-fancy'
brew 'direnv'
brew 'mise'
brew 'powerlevel10k'

# formulae pulled in for advanced configs (these are optional, but still recommended)
brew 'bat'
brew 'btop'
brew 'eza'
brew 'git-extras'
brew 'git-gui'
brew 'git-tools'
brew 'jhipster' # Note: downloads node latest version as depenency
brew 'prettyping'
brew 'sonar-scanner'

cask 'aldente'
cask 'android-studio'
cask 'appcleaner'
cask 'firefox'
cask 'flutter' # Note: downloads dart latest version as depenency
cask 'font-meslo-lg-nerd-font'
cask 'google-chrome'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'jordanbaird-ice'
cask 'keepingyouawake'
cask 'keybase'
cask 'rancher'
cask 'raycast'
cask 'stats'
cask 'vscodium'
cask 'whatsapp'
cask 'zoom'

is_vscode_installed = !`which code`.chomp.empty?
if is_vscode_installed
  # This is failing on different machines
  # vscode 'formulahendry.code-runner'
  # vscode 'nicolasvuillamy.vscode-groovy-lint'
  # vscode 'redhat.java'
  # vscode 'sonarsource.sonarlint-vscode'
  # vscode 'vscjava.vscode-java-debug'
  # vscode 'vscjava.vscode-java-pack'
  # vscode 'vscjava.vscode-java-test'
  # vscode 'vscjava.vscode-lombok'
  vscode 'brandonkirbyson.vscode-animations'
  vscode 'britesnow.vscode-toggle-quotes'
  vscode 'dart-code.dart-code'
  vscode 'dart-code.flutter'
  vscode 'davidanson.vscode-markdownlint'
  vscode 'dbaeumer.vscode-eslint'
  vscode 'digitalbrainstem.javascript-ejs-support'
  vscode 'drcika.apc-extension'
  vscode 'eamodio.gitlens'
  vscode 'editorconfig.editorconfig'
  vscode 'esbenp.prettier-vscode'
  vscode 'formulahendry.code-runner'
  vscode 'genuitecllc.codetogether'
  vscode 'golang.go'
  vscode 'ibm.output-colorizer'
  vscode 'markosth09.color-picker'
  vscode 'mechatroner.rainbow-csv'
  vscode 'mikestead.dotenv'
  vscode 'mkhl.direnv'
  vscode 'ms-azuretools.vscode-docker'
  vscode 'ms-vscode.vscode-typescript-next'
  vscode 'oderwat.indent-rainbow'
  vscode 'orta.vscode-jest'
  vscode 'rebornix.ruby'
  vscode 'redhat.vscode-yaml'
  vscode 'richie5um2.vscode-sort-json'
  vscode 'shan.code-settings-sync'
  vscode 'tchayen.markdown-links'
  vscode 'tyriar.sort-lines'
  vscode 'vscode-icons-team.vscode-icons'
  vscode 'wayou.vscode-todo-highlight'
  vscode 'wholroyd.jinja'
  vscode 'wingrunr21.vscode-ruby'
  vscode 'wmaurer.change-case'
  vscode 'yzhang.markdown-all-in-one'
end

# ----------------------------------------------------------------------------------------------------------
# TODO: This doesn't solve the issue about performing a custom action when a specific formula/cask is (re)installed
at_exit do
  # This removal is required for completions from other plugins to work (for eg git-extras)
  system("rm -rfv \"${HOMEBREW_REPOSITORY}/share/zsh/site-functions/_git\"") || true
end

# ----------------------------------------------------------------------------------------------------------
# Moved these brew and cask lines to clean up the noise from the above alphabetically sorted lists

# ---- zen-browser development
# brew 'gnu-tar'

# ---- docker utilities
# brew 'dive'   # docker layers inspection on steroids
# brew 'docker-diff'
# brew 'docker-slim'  # TODO: investigate if the http-probe is a deal-breaker
# brew 'hadolint'     # lint Dockerfiles (similar to shellcheck for shell scripts)
# brew 'kubernetes-cli', link: true   # Note: Had to do this: rm /usr/local/bin/kubectl && brew link --overwrite kubernetes-cli
# brew 'kubernetes-helm'

# ---- git utilities
# brew 'git-crypt'

# ---- tmux utilities
# brew 'tmux'
# brew 'reattach-to-user-namespace' # Needed if using tmux (to be able to access the macos clipboard from within tmux)

# ---- general utilities
# brew 'fzy'
# brew 'gradle-completion'
# brew 'libressl', link: true
# brew 'localstack'
# brew 'shellcheck'
# brew 'speedtest-cli'
# ---------------------------------------------------------------------------------------------------------
# mas is to download apps from app store [regester/login to app store for mas commands to work]
# ---------------------------------------------------------------------------------------------------------
# brew 'mas'

# https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git
# cask 'git-credential-manager'

# ---- casks
# cask 'clocker'
# cask 'cloudflare-warp'
# cask 'dbeaver-community'
# cask 'git-credential-manager'   # https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git
# cask 'intellij-idea-ce'
# cask 'kdiff3'
# cask 'keycastr'
# cask 'licecap'
# cask 'lulu'
# cask 'microsoft-remote-desktop'
# cask 'microsoft-teams'
# cask 'netspot'
# cask 'ngrok'
# cask 'tempbox'
